//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Programming_Practice
{
    using System;
    using System.Collections.Generic;
    
    public partial class Progress
    {
        public int ID { get; set; }
        public int User_ID { get; set; }
        public int Log_ID { get; set; }
        public int Attempt { get; set; }
    
        public virtual Log Log { get; set; }
        public virtual User User { get; set; }
    }
}
