//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Programming_Practice
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Progresses = new HashSet<Progress>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string LogInID { get; set; }
        public string Password { get; set; }
        public string Hint { get; set; }
        public System.DateTime EnrollmentDate { get; set; }
        public System.DateTime ExpiryDate { get; set; }
        public string Status { get; set; }
        public int User_Type_ID { get; set; }
        public byte[] Image { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Progress> Progresses { get; set; }
    }
}
